import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { montreal, monument } from '@/lib/fonts'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={montreal.className}>{children}</body>
		</html>
	)
}
